import { Color } from "../color";

export type Farbe = Color;
export const FarbeHex = Color.fromHex;

export const Farben = {
    "Eisfarben": Color.fromHex("#F0F8FF"),
    "Antikweiß": Color.fromHex("#FAEBD7"),
    "Wasser": Color.fromHex("#00FFFF"),
    "Aquamarinblau": Color.fromHex("#7FFFD4"),
    "Azurblau": Color.fromHex("#F0FFFF"),
    "Beige": Color.fromHex("#F5F5DC"),
    "Biskuit": Color.fromHex("#FFE4C4"),
    "Schwarz": Color.fromHex("#000000"),
    "Mandelweiß": Color.fromHex("#FFEBCD"),
    "Blau": Color.fromHex("#0000FF"),
    "Blauviolett": Color.fromHex("#8A2BE2"),
    "Braun": Color.fromHex("#A52A2A"),
    "Gelbbraun": Color.fromHex("#DEB887"),
    "Kadettenblau": Color.fromHex("#5F9EA0"),
    "Chartreuse": Color.fromHex("#7FFF00"),
    "Schokolade": Color.fromHex("#D2691E"),
    "Koralle": Color.fromHex("#FF7F50"),
    "Kornblumenblau": Color.fromHex("#6495ED"),
    "Mais": Color.fromHex("#FFF8DC"),
    "Karmesinrot": Color.fromHex("#DC143C"),
    "Cyan": Color.fromHex("#00FFFF"),
    "Dunkelblau": Color.fromHex("#00008B"),
    "Dunkelcyan": Color.fromHex("#008B8B"),
    "Dunkle Goldrutenfarbe": Color.fromHex("#B8860B"),
    "Dunkelgrün": Color.fromHex("#006400"),
    "Dunkelgrau": Color.fromHex("#A9A9A9"),
    "Dunkelkhaki": Color.fromHex("#BDB76B"),
    "Dunkelmagenta": Color.fromHex("#8B008B"),
    "Dunkles Olivgrün": Color.fromHex("#556B2F"),
    "Dunkles Orange": Color.fromHex("#FF8C00"),
    "Dunkle Orchidee": Color.fromHex("#9932CC"),
    "Dunkelrot": Color.fromHex("#8B0000"),
    "Dunkle Lachsfarbe": Color.fromHex("#E9967A"),
    "Dunkles Seegrün": Color.fromHex("#8FBC8F"),
    "Dunkles Schieferblau": Color.fromHex("#483D8B"),
    "Dunkles Schiefergrau": Color.fromHex("#2F4F4F"),
    "Dunkeltürkis": Color.fromHex("#00CED1"),
    "Dunkelvilolett": Color.fromHex("#9400D3"),
    "Tiefrosa": Color.fromHex("#FF1493"),
    "Tiefes Himmelblau": Color.fromHex("#00BFFF"),
    "Dunkeldunkelgrau": Color.fromHex("#696969"),
    "Persenningblau": Color.fromHex("#1E90FF"),
    "Backstein": Color.fromHex("#B22222"),
    "Blütenweiß": Color.fromHex("#FFFAF0"),
    "Waldgrün": Color.fromHex("#228B22"),
    "Fuchsia": Color.fromHex("#FF00FF"),
    "Gainsboro": Color.fromHex("#DCDCDC"),
    "Geisterweiß": Color.fromHex("#F8F8FF"),
    "Gold": Color.fromHex("#FFD700"),
    "Goldrute": Color.fromHex("#DAA520"),
    "Grün": Color.fromHex("#008000"),
    "Grüngelb": Color.fromHex("#ADFF2F"),
    "Grau": Color.fromHex("#808080"),
    "Honigmelone": Color.fromHex("#F0FFF0"),
    "Leuchtendes Rosa": Color.fromHex("#FF69B4"),
    "Indischrot": Color.fromHex("#CD5C5C"),
    "Indigo": Color.fromHex("#4B0082"),
    "Elfenbein": Color.fromHex("#FFFFF0"),
    "Staubfarben": Color.fromHex("#F0E68C"),
    "Lavendel": Color.fromHex("#E6E6FA"),
    "Lavendelrosa": Color.fromHex("#FFF0F5"),
    "Rasengrün": Color.fromHex("#7CFC00"),
    "Chiffongelb": Color.fromHex("#FFFACD"),
    "Hellblau": Color.fromHex("#ADD8E6"),
    "Helles Korallenrot": Color.fromHex("#F08080"),
    "Helles Cyan": Color.fromHex("#E0FFFF"),
    "Helles Goldrutengelb": Color.fromHex("#FAFAD2"),
    "Hellgrau": Color.fromHex("#D3D3D3"),
    "Hellgrün": Color.fromHex("#90EE90"),
    "Hellrosa": Color.fromHex("#FFB6C1"),
    "Helle Lachsfarbe": Color.fromHex("#FFA07A"),
    "Helles Seegrün": Color.fromHex("#20B2AA"),
    "Helles Himmelblau": Color.fromHex("#87CEFA"),
    "Helles Schiefergrau": Color.fromHex("#778899"),
    "Helles Stahlblau": Color.fromHex("#B0C4DE"),
    "Hellgelb": Color.fromHex("#FFFFE0"),
    "Limone": Color.fromHex("#00FF00"),
    "Limonengrün": Color.fromHex("#32CD32"),
    "Leinen": Color.fromHex("#FAF0E6"),
    "Magenta": Color.fromHex("#FF00FF"),
    "Kastanie": Color.fromHex("#800000"),
    "Mittleres Aquamarin": Color.fromHex("#66CDAA"),
    "Mittleres Blau": Color.fromHex("#0000CD"),
    "Mittlere Orchidee": Color.fromHex("#BA55D3"),
    "Mittleres Violett": Color.fromHex("#9370DB"),
    "Mittleres Seegrün": Color.fromHex("#3CB371"),
    "Mittleres Schieferblau": Color.fromHex("#7B68EE"),
    "Mittleres Frühlingsgrün": Color.fromHex("#00FA9A"),
    "Mittlere Türkis": Color.fromHex("#48D1CC"),
    "Mittleres Violettrot": Color.fromHex("#C71585"),
    "Mitternachtsblau": Color.fromHex("#191970"),
    "Cremige Minze": Color.fromHex("#F5FFFA"),
    "Altrosa": Color.fromHex("#FFE4E1"),
    "Mokassin": Color.fromHex("#FFE4B5"),
    "Navajoweiß": Color.fromHex("#FFDEAD"),
    "Marinenblau": Color.fromHex("#000080"),
    "Alte Spitze": Color.fromHex("#FDF5E6"),
    "Olivgrün": Color.fromHex("#808000"),
    "Olivgraubraun": Color.fromHex("#6B8E23"),
    "Orange": Color.fromHex("#FFA500"),
    "Orangerot": Color.fromHex("#FF4500"),
    "Orchidee": Color.fromHex("#DA70D6"),
    "Blasse Goldrutenfarbe": Color.fromHex("#EEE8AA"),
    "Blassgrün": Color.fromHex("#98FB98"),
    "Blasstürkis": Color.fromHex("#AFEEEE"),
    "Blasses Violettrot": Color.fromHex("#DB7093"),
    "Papayacreme": Color.fromHex("#FFEFD5"),
    "Pfirsich": Color.fromHex("#FFDAB9"),
    "Peru": Color.fromHex("#CD853F"),
    "Rosa": Color.fromHex("#FFC0CB"),
    "Pflaume": Color.fromHex("#DDA0DD"),
    "Taubenblau": Color.fromHex("#B0E0E6"),
    "Purpur": Color.fromHex("#800080"),
    "Rot": Color.fromHex("#FF0000"),
    "Rosiges Braun": Color.fromHex("#BC8F8F"),
    "Königsbalu": Color.fromHex("#4169E1"),
    "Sattelbraun": Color.fromHex("#8B4513"),
    "Lachsfarben": Color.fromHex("#FA8072"),
    "Sandbraun": Color.fromHex("#F4A460"),
    "Seegrün": Color.fromHex("#2E8B57"),
    "Muschel": Color.fromHex("#FFF5EE"),
    "Siennaerde": Color.fromHex("#A0522D"),
    "Silber": Color.fromHex("#C0C0C0"),
    "Himmelblau": Color.fromHex("#87CEEB"),
    "Schieferblau": Color.fromHex("#6A5ACD"),
    "Schiefergrau": Color.fromHex("#708090"),
    "Schneeweiß": Color.fromHex("#FFFAFA"),
    "Frühlingsgrün": Color.fromHex("#00FF7F"),
    "Stahlblau": Color.fromHex("#4682B4"),
    "Hautfarben": Color.fromHex("#D2B48C"),
    "Krickentengrün": Color.fromHex("#008080"),
    "Distel": Color.fromHex("#D8BFD8"),
    "Tomate": Color.fromHex("#FF6347"),
    "Türkis": Color.fromHex("#40E0D0"),
    "Veilchen": Color.fromHex("#EE82EE"),
    "Weizen": Color.fromHex("#F5DEB3"),
    "Weiß": Color.fromHex("#FFFFFF"),
    "Blanco Humo": Color.fromHex("#F5F5F5"),
    "Gelb": Color.fromHex("#FFFF00"),
    "Gelbgrün": Color.fromHex("#9ACD32"),
   };